image: "ruby:2.6.0"

services:
  - postgres:latest

variables:
  POSTGRES_DB: work_test

cache:
  paths:
    - vendor/ruby

before_script:
  - cp config/database.ci.yml config/database.yml
  - bundle install -j $(nproc) --path vendor

rubocop:
  script:
  - bundle exec rubocop

rspec:
  script:
  - bundle exec rspec

